export const roomsData = [
  {
    id: 104,
    roomNumber: '104',
    floor: 'Primer piso',
    status: 'Abierto',
    isAvailability: true,
    observations: [],
    tasks: [],
  },
  {
    id: 108,
    roomNumber: '108',
    floor: 'Segundo piso',
    status: 'Abierto',
    isAvailability: true,
    observations: [],
    tasks: [],
  },
  {
    id: 109,
    roomNumber: '109',
    floor: 'Tercer piso',
    status: 'Cerrado',
    isAvailability: false,
    observations: [],
    tasks: [],
  },
  {
    id: 110,
    roomNumber: '110',
    floor: 'Tercer piso',
    status: 'Abierto',
    isAvailability: true,
    observations: [],
    tasks: [],
  },
  {
    id: 111,
    roomNumber: '111',
    floor: 'Cuarto piso',
    status: 'Cerrado',
    isAvailability: false,
    observations: [],
    tasks: [],
  },
  {
    id: 112,
    roomNumber: '112',
    floor: 'Cuarto piso',
    status: 'Abierto',
    isAvailability: true,
    observations: [],
    tasks: [],
  },
  {
    id: 113,
    roomNumber: '113',
    floor: 'Quinto piso',
    status: 'Abierto',
    isAvailability: true,
    observations: [],
    tasks: [],
  },
  {
    id: 114,
    roomNumber: '114',
    floor: 'Quinto piso',
    status: 'Cerrado',
    isAvailability: false,
    observations: [],
    tasks: [],
  },
  {
    id: 115,
    roomNumber: '115',
    floor: 'Sexto piso',
    status: 'Cerrado',
    isAvailability: false,
    observations: [],
    tasks: [],
  },
  {
    id: 116,
    roomNumber: '116',
    floor: 'Sexto piso',
    status: 'Abierto',
    isAvailability: true,
    observations: [],
    tasks: [],
  },
  {
    id: 117,
    roomNumber: '117',
    floor: 'Séptimo piso',
    status: 'Abierto',
    isAvailability: true,
    observations: [],
    tasks: [],
  },
];
