export const staffData = [
  {
    _id: 1,
    nameComplete: 'Juan Pérez',
    user: 'usmpfca1',
    isActive: true,
    number: '987654321',
    email: 'juanPe2021@gmail.com',
    password: '123456',
  },
  {
    _id: 2,
    nameComplete: 'María Sánchez',
    user: 'usmpfca2',
    isActive: true,
    number: '924254322',
    email: 'maria_sanchez@gmail.com',
    password: '123456',
  },
  {
    _id: 3,
    nameComplete: 'Ana Martínez',
    user: 'usmpfca3',
    isActive: true,
    number: '977888999',
    email: 'ana_m21@hotmail.com',
    password: 'passAna456',
  },
  {
    _id: 4,
    nameComplete: 'Luis Rodríguez',
    user: 'usmpfca4',
    isActive: false,
    number: '912345678',
    email: 'Garcialuis@hotmail.com',
    password: 'luispass',
  },
];
